Add minikube installation instructions
seecloud/oss-ccp pull request #1
Opened 2016-12-12 12:00 UTC by ivanovmi

- Add guide with initial steps for using minikube and ccp
- Add common script for helping to setup env

2016-12-12 13:03 UTC, akscram commented on minikube/minikube.md
> +After these steps, you can clone [ccp repo](http://github.com/openstack/fuel-ccp), and install it with instructions. After config generation, you can start using our ccp definition:
Which instructions do you mean by mentioning them here? Could you please provide a link or write step-by-step instructions?

2016-12-12 13:09 UTC, akscram commented on minikube/minikube.sh
> +  for YAML in service-account.yaml es-svc.yaml es-rc.yaml ; do
It would be greate to place this configuration files statically into `minikube/elasticsearch` to be sure that everything works.

2016-12-12 13:16 UTC, akscram commented on minikube/minikube.sh
> +  namespace: default
Please, use the `oss` environment, also, to configure `kubectl` to use this environment add the following commands in the scripts:

```
kubectl config set-context oss --namespace oss
kubectl config use-context oss
```

2016-12-12 13:17 UTC, akscram commented on minikube/minikube.sh
> +    - performance
Until the performance service is not described for `ccp` let's comment or remove this line.

2016-12-12 13:18 UTC, akscram requested changes
Please, fix my inline comments.

2016-12-13 09:12 UTC, akscram requested changes

2016-12-13 09:12 UTC, akscram commented on minikube/minikube.sh
> +  echo " -s - change kubectl context to oss"
Please, add this new command into README or just call this as a part of of the `generate_config` function.

2016-12-13 09:12 UTC, akscram commented on minikube/minikube.sh
> +  for YAML in service-account.yaml es-svc.yaml es-rc.yaml ; do
You leave my comment unnoticed about keeping these files locally and do not try to download them.

2016-12-13 10:06 UTC, ivanovmi commented on minikube/minikube.sh
> +  for YAML in service-account.yaml es-svc.yaml es-rc.yaml ; do
Oh, sorry, I just misunderstood you

2016-12-13 10:09 UTC, ivanovmi commented on minikube/minikube.sh
> +  echo " -s - change kubectl context to oss"
Added info about `-s` to README

2016-12-13 11:07 UTC, akscram approved these changes

2016-12-13 14:51 UTC, akscram approved these changes

2016-12-13 14:53 UTC, merged